const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
  JSON_PARSE_ERROR: 'JSON_PARSE_ERROR',
};

const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  NEW: 'NEW',
  DELETE: 'DELETE',
};

module.exports.ERROR_CODE = ERROR_CODE;
module.exports.PRODUCT_STATUS = PRODUCT_STATUS;
